Normalize line endings

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -5,13 +5,24 @@
 #fi;
 
 #  *using java 17*
-#  mvn clean package -Dskiptests
+#  mvn clean package -DskipTests
 #  docker-compose build
 #  docker-compose down -v --remove-orphans
 #  docker run --rm --privileged=true alpine:latest sysctl -w vm.max_map_count=262144
 #  docker-compose up -d
 #  docker ps
 
+##Copiar certificado do container do elasticsearch para uma pasta (Temp no caso)##
+#docker cp es01:/usr/share/elasticsearch/config/certs/ca/ca.crt C:\Temp\.
+
+#extrair fingerprint do certificado sem openssl (abrir no powershell) ->
+##Copia para uma variavel do powershell##
+# $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2("C:\Temp\ca.crt")
+##calcula o fingerprint##
+#$fingerprint = $cert.GetCertHashString("SHA256")
+#$fingerprint
+##Resultado parecido com o valor abaixo
+# 0441E5C711506DD59808E25B926FBB14164E5BCC00A8C15F4B0EB5BB2C4DC911
 
 version: "3.8"
 
@@ -28,6 +39,10 @@ volumes:
     driver: local
   logstashdata01:
     driver: local
+  fleetserverdata:
+    driver: local
+#  apmdata:
+#    driver: local
 
 networks:
   default:
@@ -58,7 +73,7 @@ services:
         if [ ! -f config/certs/certs.zip ]; then
           echo "Creating certs";
           echo -ne \
-          "instances:\n"\
+           "instances:\n"\
           "  - name: es01\n"\
           "    dns:\n"\
           "      - es01\n"\
@@ -71,9 +86,9 @@ services:
           "      - localhost\n"\
           "    ip:\n"\
           "      - 127.0.0.1\n"\
-          "  - name: otel-collector\n"\
+          "  - name: fleet-server\n"\
           "    dns:\n"\
-          "      - otel-collector\n"\
+          "      - fleet-server\n"\
           "      - localhost\n"\
           "    ip:\n"\
           "      - 127.0.0.1\n"\
@@ -99,9 +114,9 @@ services:
 
   es01:
     container_name: es01
-    depends_on:
-      setup:
-        condition: service_healthy
+#    depends_on:
+#      setup:
+#        condition: service_healthy
     image: registry-docker.weg.net/elasticsearch:${STACK_VERSION}
     labels:
       co.elastic.logs/module: elasticsearch
@@ -127,7 +142,8 @@ services:
       - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
       - xpack.security.transport.ssl.verification_mode=certificate
       - xpack.license.self_generated.type=${LICENSE}
-      - ES_JAVA_OPTS=-Xms512m -Xmx512m
+      - ES_JAVA_OPTS=-Xms256m -Xmx256m
+      - http.max_content_length=100mb
     mem_limit: ${ES_MEM_LIMIT}
     ulimits:
       memlock:
@@ -148,6 +164,12 @@ services:
     depends_on:
       es01:
         condition: service_healthy
+      package-registry:
+        condition: service_healthy
+#      fleet-server:
+#        condition: service_healthy
+#      package-registry:
+#        condition: service_healthy
     image: registry-docker.weg.net/kibana:${STACK_VERSION}
 #    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
     labels:
@@ -155,9 +177,11 @@ services:
     volumes:
       - certs:/usr/share/kibana/config/certs
       - kibanadata:/usr/share/kibana/data
+      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
     ports:
       - ${KIBANA_PORT}:5601
     environment:
+      - xpack.fleet.registryUrl=http://package-registry:8080
       - SERVERNAME=kibana
       - ELASTICSEARCH_HOSTS=https://es01:9200
       - ELASTICSEARCH_USERNAME=kibana_system
@@ -166,13 +190,19 @@ services:
       - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
       - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
       - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}
-#      - xpack.fleet.agents.enabled=false
+      - XPACK_REPORTING_KIBANASERVER_HOSTNAME=localhost
+      - SERVER_SSL_ENABLED=true
+      - SERVER_SSL_CERTIFICATE=config/certs/kibana/kibana.crt
+      - SERVER_SSL_KEY=config/certs/kibana/kibana.key
+      - SERVER_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
+      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN}
+      - xpack.fleet.isAirGapped=true
     mem_limit: ${KB_MEM_LIMIT}
     healthcheck:
       test:
         [
           "CMD-SHELL",
-          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
+          "curl -s -I https://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
         ]
       interval: 10s
       timeout: 10s
@@ -199,8 +229,13 @@ services:
       - ELASTIC_USER=elastic
       - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
       - ELASTIC_HOSTS=https://es01:9200
-      - KIBANA_HOSTS=http://kibana:5601
+      - KIBANA_HOSTS=https://kibana:5601
       - LOGSTASH_HOSTS=http://logstash01:9600
+      - CA_CERT=certs/ca/ca.crt
+      - ES_CERT=certs/es01/es01.crt
+      - ES_KEY=certs/es01/es01.key
+      - KB_CERT=certs/kibana/kibana.crt
+      - KB_KEY=certs/kibana/kibana.key
     command:
       - --strict.perms=false
 
@@ -222,16 +257,17 @@ services:
       - ELASTIC_USER=elastic
       - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
       - ELASTIC_HOSTS=https://es01:9200
-      - KIBANA_HOSTS=http://kibana:5601
+      - KIBANA_HOSTS=https://kibana:5601
       - LOGSTASH_HOSTS=http://logstash01:9600
+      - CA_CERT=certs/ca/ca.crt
     command:
       - --strict.perms=false
 
   logstash01:
     container_name: logstash01
-    depends_on:
-      kibana:
-        condition: service_healthy
+#    depends_on:
+#      kibana:
+#        condition: service_healthy
     image: registry-docker.weg.net/logstash:${STACK_VERSION}
     labels:
       co.elastic.logs/module: logstash
@@ -250,14 +286,16 @@ services:
 #      - "5044:5044"
 
   otel-collector:
-    image: registry-docker.weg.net/otel/opentelemetry-collector-contrib:latest
+#    image: registry-docker.weg.net/otel/opentelemetry-collector-contrib:latest
+    image: registry-docker.weg.net/otel/opentelemetry-collector:latest
     container_name: otel-collector
     volumes:
       - ./otel-collector-config.yml:/otel-local-config.yaml
       - certs:/etc/otel/ssl  # Volume para os certificados, incluindo o certificado OTel Collector
     environment:
       - ELASTICSEARCH_HOST=https://es01:9200
-      - ELASTICSEARCH_USERNAME=kibana_system
+#      - ELASTICSEARCH_USERNAME=kibana_system
+      - ELASTICSEARCH_USERNAME=elastic
       - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
       - xpack.security.transport.ssl.certificate_authorities=/etc/otel/ssl/ca.crt
       - ELASTICSEARCH_CA_PATH=/usr/share/otel/ca.crt  # Caminho para o certificado CA do Elasticsearch
@@ -265,9 +303,10 @@ services:
 #      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
 #      - ELASTICSEARCH_CA_PATH=/usr/share/otel/ca.crt # Caminho para o certificado CA do Elasticsearch
     command: ["--config", "/otel-local-config.yaml"]
-#    ports:
+    ports:
 #      - "4317:4317" # OTLP gRPC
-#      - "55681:55681" # OTLP HTTP
+      - "55681:55681" # OTLP HTTP
+      - "4318:4318" # OTLP HTTP
 
   observability-test:
     image: observability-test:latest
@@ -276,9 +315,102 @@ services:
       context: .
       dockerfile: Dockerfile
     ports:
-      - "8080:8080"
+      - "9090:9090"
     environment:
       - SPRING_PROFILES_ACTIVE=prod
     depends_on:
       - otel-collector
       - kibana
+
+
+  fleet-server:
+    container_name: fleet-server
+    depends_on:
+#      kibana:
+#        condition: service_healthy
+      es01:
+        condition: service_healthy
+    image: registry-docker.weg.net/beats/elastic-agent:${STACK_VERSION}
+    volumes:
+      - certs:/certs
+      - fleetserverdata:/usr/share/elastic-agent
+      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
+      - "/var/run/docker.sock:/var/run/docker.sock:ro"
+      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
+      - "/proc:/hostfs/proc:ro"
+      - "/:/hostfs:ro"
+    ports:
+      - ${FLEET_PORT}:8220
+      - ${APMSERVER_PORT}:8200
+    user: root
+    environment:
+      - ELASTICSEARCH_HOST=https://es01:9200
+      - ELASTICSEARCH_HOSTS=https://es01:9200
+      - ELASTICSEARCH_USERNAME=elastic
+      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
+      - SSL_CERTIFICATE_AUTHORITIES=/certs/ca/ca.crt
+      - CERTIFICATE_AUTHORITIES=/certs/ca/ca.crt
+      - FLEET_CA=/certs/ca/ca.crt
+      - FLEET_ENROLL=1
+      - FLEET_INSECURE=true
+      - FLEET_SERVER_ELASTICSEARCH_CA=/certs/ca/ca.crt
+      - FLEET_SERVER_ELASTICSEARCH_HOST=https://es01:9200
+      - fleet-server-es=https://es01:9200
+      - fleet_server_es=https://es01:9200
+      - fleet_server_elasticsearch=https://es01:9200
+      - FLEET_SERVER_ELASTICSEARCH_INSECURE=true
+      - FLEET_SERVER_ENABLE=1
+      - FLEET_SERVER_CERT=/certs/fleet-server/fleet-server.crt
+      - FLEET_SERVER_CERT_KEY=/certs/fleet-server/fleet-server.key
+      - FLEET_SERVER_INSECURE_HTTP=true
+      - FLEET_SERVER_POLICY_ID=fleet-server-policy
+      - FLEET_URL=https://fleet-server:8220
+      - KIBANA_FLEET_CA=/certs/ca/ca.crt
+      - KIBANA_FLEET_SETUP=1
+      - KIBANA_FLEET_USERNAME=elastic
+      - KIBANA_FLEET_PASSWORD=${ELASTIC_PASSWORD}
+      - KIBANA_HOST=https://kibana:5601
+      - xpack.fleet.agents.elasticsearch.hosts=https://es01:9200
+#    healthcheck:
+#      test:
+#        [
+#          "CMD-SHELL",
+#          "curl -s -f http://localhost:8220/_health || exit 1",
+#        ]
+#      interval: 10s
+#      timeout: 10s
+#      retries: 120
+
+  package-registry:
+    image: registry-docker.weg.net/package-registry/distribution:lite-${STACK_VERSION}
+#    image: registry-docker.weg.net/package-registry/distribution:8.14.3
+    container_name: package-registry
+    ports:
+      - "8080:8080"
+
+#  curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.7.1-linux-x86_64.tar.gz
+#  tar xzvf elastic-agent-8.7.1-linux-x86_64.tar.gz
+#  cd elastic-agent-8.7.1-linux-x86_64
+#  sudo ./elastic-agent install \
+#  --fleet-server-es=http://localhost:9200 \
+#  --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE3MjE0MTEwMzE5NTU6OXY5ME9velJUWHFwa3ZBTnpKWWJ0QQ \
+#  --fleet-server-policy=fleet-server-policy
+
+#  apm-server:
+#    container_name: apm-server
+#    image: registry-docker.weg.net/apm/apm-server:${STACK_VERSION}
+#    depends_on:
+#      es01:
+#        condition: service_healthy
+#    ports:
+#      - "8200:8200"
+#    volumes:
+#      - certs:/usr/share/apm-server/config/certs
+#      - apmdata:/usr/share/apm-server/data
+#    environment:
+#      - ELASTICSEARCH_HOSTS=https://es01:9200
+#      - ELASTICSEARCH_USERNAME=elastic
+#      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
+#      - output.elasticsearch.ssl.certificate_authorities=config/certs/ca/ca.crt
+#      - output.elasticsearch.ssl.certificate=config/certs/apm-server/apm-server.crt
+#      - output.elasticsearch.ssl.key=config/certs/apm-server/apm-server.key
